import * as Lucide from 'lucide-react';

export const Icons = {
  Utensils: Lucide.Utensils,
  Car: Lucide.Car,
  Gamepad2: Lucide.Gamepad2,
  HeartPulse: Lucide.HeartPulse,
  GraduationCap: Lucide.GraduationCap,
  Home: Lucide.Home,
  Wallet: Lucide.Wallet,
  CreditCard: Lucide.CreditCard,
  TrendingUp: Lucide.TrendingUp,
  MoreHorizontal: Lucide.MoreHorizontal,
  Plus: Lucide.Plus,
  Minus: Lucide.Minus,
  ArrowUpRight: Lucide.ArrowUpRight,
  ArrowDownLeft: Lucide.ArrowDownLeft,
  Calendar: Lucide.Calendar,
  Tag: Lucide.Tag,
  Trash2: Lucide.Trash2,
  Edit2: Lucide.Edit2,
  LogOut: Lucide.LogOut,
  User: Lucide.User,
  LayoutDashboard: Lucide.LayoutDashboard,
  List: Lucide.List,
  Settings: Lucide.Settings,
  ChevronRight: Lucide.ChevronRight,
  ChevronLeft: Lucide.ChevronLeft,
  Search: Lucide.Search,
  Filter: Lucide.Filter,
  Download: Lucide.Download,
  Sparkles: Lucide.Sparkles,
  AlertCircle: Lucide.AlertCircle,
  Landmark: Lucide.Landmark,
  X: Lucide.X,
  ChevronDown: Lucide.ChevronDown,
  Check: Lucide.Check,
  Target: Lucide.Target,
  Plane: Lucide.Plane,
  Shield: Lucide.Shield,
  Briefcase: Lucide.Briefcase,
  CheckCircle: Lucide.CheckCircle,
  Trophy: Lucide.Trophy,
  Flag: Lucide.Flag,
  Quote: Lucide.Quote,
};

export type IconName = keyof typeof Icons;
