CREATE TABLE `user_settings` (
  `id`                     VARCHAR(36)  NOT NULL,
  `user_id`                VARCHAR(36)  NOT NULL,
  `email_notifications`    TINYINT(1)   NOT NULL DEFAULT 1,
  `weekly_report`          TINYINT(1)   NOT NULL DEFAULT 1,
  `monthly_report`         TINYINT(1)   NOT NULL DEFAULT 1,
  `push_notifications`     TINYINT(1)   NOT NULL DEFAULT 1,
  `reminder_advance_days`  INT          NOT NULL DEFAULT 3,
  `reminder_frequency`     VARCHAR(20)  NOT NULL DEFAULT 'daily',
  `budget_alert_threshold` INT          NOT NULL DEFAULT 80,
  `low_balance_alert`      DOUBLE       NOT NULL DEFAULT 100,
  `large_transaction_alert` DOUBLE      NOT NULL DEFAULT 500,
  `credit_usage_alert`     INT          NOT NULL DEFAULT 70,
  `emergency_fund_months`  DOUBLE       NOT NULL DEFAULT 6,
  `savings_rate_target`    INT          NOT NULL DEFAULT 20,
  `debt_income_limit`      INT          NOT NULL DEFAULT 30,
  `risk_profile`           VARCHAR(20)  NOT NULL DEFAULT 'moderate',
  `rebalance_alert`        TINYINT(1)   NOT NULL DEFAULT 1,
  `rebalance_threshold`    INT          NOT NULL DEFAULT 5,
  `fixed_income_target`    INT          NOT NULL DEFAULT 40,
  `variable_target`        INT          NOT NULL DEFAULT 40,
  `international_target`   INT          NOT NULL DEFAULT 20,
  `show_market_news`       TINYINT(1)   NOT NULL DEFAULT 1,
  `show_economic_news`     TINYINT(1)   NOT NULL DEFAULT 1,
  `show_personal_tips`     TINYINT(1)   NOT NULL DEFAULT 1,
  `created_at`             DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at`             DATETIME(3)  NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_settings_user_id_key` (`user_id`),
  CONSTRAINT `user_settings_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
